CAMPAIGN_STATUS = [
    "DRAFT",
    "BRIEF_EXTRACTED",
    "CONTEXT_RETRIEVED",
    "VARIANTS_GENERATED",
    "COMPLIANCE_CHECKED",
    "NEEDS_REVIEW",
    "APPROVED",
    "SENT",
    "MOCK_PAYLOAD_READY",
    "FAILED",
]

VARIANT_STATUS = ["GENERATED", "COMPLIANCE_PASSED", "COMPLIANCE_FAILED", "APPROVED", "REJECTED"]
DOCUMENT_STATUS = ["UPLOADED", "INGESTING", "INGESTED", "FAILED"]
CHANNELS = ["telegram", "whatsapp_mock"]
